# Generated by Django 3.2 on 2024-11-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva2App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='DBproyecto',
            new_name='Cliente',
        ),
    ]
