# Generated by Django 3.2 on 2024-11-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva2App', '0002_auto_20241103_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('n_paginas', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('autor', models.ManyToManyField(related_name='libros', to='eva2App.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='libros_comprados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='eva2App.libro'),
        ),
    ]
